version: '3'

volumes:
  postgres_data: {}

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  django:
    depends_on:
      - db
    build: .
    volumes:
      - .:/app/
    expose:
      - 8000
    ports:
      - "8000:8000"
    command: bash run_django.sh
    environment:
      READ_DOT_ENV_FILE: "true"
