version: '3'

volumes:
  postgres_data: {}

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
  django: &django
    depends_on:
      - db
      - redis
    build: .
    volumes:
      - .:/app/
    ports:
      - "8000:8000"
    command: bash run_django.sh
  celery:
    <<: *django
    ports: []
    command: celery -A mylibrary worker -l info
