# Generated by Django 2.2.1 on 2019-06-04 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookprice',
            unique_together={('book', 'supplier')},
        ),
    ]
